const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categories/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCESS: "categories/FETCH_CATEGORIES_SUCESS",
  FETCH_CATEGORIES_FAILED: "categories/FETCH_CATEGORIES_FAILED",
};

export default CATEGORIES_ACTION_TYPES;
